#!/usr/bin/env zsh

# ZDOTDIR/.zprofile: executed by zsh(1)
# Will be read when starting as a login shell (spawned by a TTY or by a SSH daemon)

# Execute Message of the Day script
if [ "$(command -v motd)" ]; then
  motd
fi

export GPG_TTY=$(tty)
