# Symlink Cask apps in /Applications
cask_args appdir: '/Applications'

# Taps
tap 'homebrew/completions'

# Commandline tools
brew 'ack'
brew 'archey'
brew 'awscli'
brew 'bash'
brew 'bats'
brew 'docker'
brew 'docker-compose'
brew 'docker-machine'
brew 'fortune'
brew 'git'
brew 'go'
brew 'gpg-agent'
brew 'htop'
brew 'hub'
brew 'kubernetes-cli'
brew 'lynx'
brew 'midnight-commander'
brew 'nmap'
brew 'openssl'
brew 'packer'
brew 'pstree'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'reattach-to-user-namespace'
brew 'rbenv'
brew 'task'
brew 'terminal-notifier'
brew 'terraform'
brew 'tmux'
brew 'tree'
brew 'vault'
brew 'vim'
brew 'wget'

# Shell autocomplete
brew 'bash-completion'
brew 'brew-cask-completion'
brew 'docker-completion'
brew 'docker-compose-completion'
brew 'docker-machine-completion'
brew 'open-completion'
brew 'packer-completion'
brew 'pip-completion'
brew 'vagrant-completion'

# Dependencies
brew 'autoconf'
brew 'gettext'
brew 'glib'
brew 'gmp'
brew 'gnutls'
brew 'libassuan'
brew 'libelf'
brew 'libevent'
brew 'libffi'
brew 'libftdi0'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libksba'
brew 'libpng'
brew 'libssh2'
brew 'libtasn1'
brew 'libusb'
brew 'libusb-compat'
brew 'nettle'
brew 'pinentry'
brew 'pkg-config'
brew 'pth'
brew 'readline'
brew 'ruby-build'
brew 's-lang'

# Desktop apps
# cask 'airmail-beta' # from Caskroom/versions/airmail-beta
cask 'adium'
cask 'atom'
cask 'calibre'
cask 'chromium'
cask 'cyberduck'
cask 'dash'
cask 'disk-inventory-x'
cask 'evernote'
cask 'filebot'
cask 'firefox'
cask 'flux'
cask 'gpgtools'
cask 'iterm2'
cask 'keepassx'
cask 'libreoffice'
cask 'macdown'
cask 'mplayerx'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'textmate'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'

# Experimental
brew 'avrdude'
brew 'awscli'
brew 'hugo'
brew 'irssi'
tap 'homebrew/games'
brew 'ckan'
