#!/usr/bin/env bash

# ~/.bashrc: executed by bash(1) non-login shells (spawned by a Terminal Emulator)

# If not running interactively, don't do anything else
case $- in
  *i*) ;;
    *) return;;
esac

# XDG base directories
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-'~/.cache'}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-'~/.config'}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-'~/.local/share'}"

# Source BASH login and non-login configuration
[ -r "${XDG_CONFIG_HOME}/bash/login.sh" ] && source "${XDG_CONFIG_HOME}/bash/login.sh"
[ -r "${XDG_CONFIG_HOME}/bash/non-login.sh" ] && source "${XDG_CONFIG_HOME}/bash/non-login.sh"

# Source shared numbered config files
for file in "${XDG_CONFIG_HOME}/shell/"[0-9][0-9]_*.sh; do
  [ -r "$file" ] && source "$file"
done
