#!/usr/bin/env bash

# ~/.bashrc: executed by bash(1) non-login shells (spawned by a Terminal Emulator)

# If not running interactively, don't do anything else
case $- in
  *i*) ;;
    *) return;;
esac

# Source BASH profile (~/.bash_profile)
[ -r ~/.bash_profile ] && source ~/.bash_profile

# Checks the window size after each command and, if necessary,
# updates the values of LINES and COLUMNS
shopt -s checkwinsize

# Set TERM variables
TERM='xterm-256color'
# shellcheck disable=SC2034
COLORTERM='truecolor'

##
## Tools
##

# Load direnv (if installed)
if [ "$(command -v direnv)" ]; then
  eval "$(direnv hook bash)"
fi

# Load startship prompt (if installed)
if [ "$(command -v starship)" ]; then
  eval "$(starship init bash)"
fi
