#!/usr/bin/env zsh

# ~/.zshenv: executed by zsh(1), always
 
# Used for setting user's environment variables
# It should not contain commands that produce output or assume the shell is attached to a tty

# XDG base directories
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

# Set ZSH config directory
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
