#!/usr/bin/env bash


# File
export HISTFILE=$HOME/.bash_history
# Size
export HISTSIZE=32768
# Avoid duplicates
export HISTCONTROL=ignoredups:erasedups
# Ignore
export HISTIGNORE='&:ls:cd ~:cd ..:pwd:clear:[bf]g:exit:h:history'
# Timestamps for later analysis. www.debian-administration.org/users/rossen/weblog/1
export HISTTIMEFORMAT='%F %T '
# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
# After each command, append to the history file and reread it
#export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; #history -c; history -r"

