#!/usr/bin/env bash


alias  v='ls -lhA'
alias vs='ls -lhASr'  # Sort by size-reversed
alias vt='ls -lhAtr'  # Sort by mtime-reversed
alias vx='ls -lhAe@'  # Show ACLs and xattrs

alias d='du -csh | sort -nk'
alias df='df -h'
alias ln='ln -v'
alias mkdir='mkdir -p'
alias mv='mv -vi'
alias rm='rm -v'

alias grep='grep --color=auto'
alias mate='mate --no-wait'
alias mc='mc -a'
alias tmux='tmux -2'
alias tree='tree -aC -I .git --dirsfirst'

alias clean_DS_Store='find . -name *.DS_Store -type f -print -delete'

