#!/usr/bin/env bash


function load_all_completions() {
  command -v brew >/dev/null 2>&1 || { 
    echo >&2 "Homebrew not found. Aborting BASH completion."; return 1; }

  brew list bash-completion2 >/dev/null 2>&1 || {
    echo >&2 "Homebrew bash-completion2 not found. Aborting BASH completion."; return 1; }

  local cpath="$(brew --prefix)/etc/bash_completion.d"
  local disabled="$cpath/git-prompt.sh $cpath/hg-completion.bash"

  for fname in "$cpath"/*; do
    [[ ! " $disabled " =~ " $fname " ]] && [ -f "$fname" ] && source "$fname"
  done

  # homebrew/versions/bash-completion2
  if [ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]; then
    source "$(brew --prefix)/share/bash-completion/bash_completion"
  fi
}

load_all_completions && unset load_all_completions
