#!/usr/bin/env bash


# PS1 – Default interaction prompt
# #export PS1="[\!]\[\033[1;25m\][\t]\[\033[1;33m\]\u\[\033[0m\]@\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\`\H\[\033[0m\]:\[\033[1;25m\]<\w>\[\033[0m\]# "

# PS2 – Continuation interactive prompt
export PS2='  '

# PS4 - Prefix tracing output (set -x)
export PS4='$0.$LINENO+ '

