#!/usr/bin/env bash
# shellcheck disable=SC1090

# ~/.config/bash/rc: executed by bash(1) shells

[[ $DISPLAY ]] && shopt -s checkwinsize

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# History: file
HISTFILE="$XDG_DATA_HOME"/bash/history

# History: size
HISTSIZE=4096

# History: avoid duplicates
HISTCONTROL=ignoredups:erasedups

# History: ignore
HISTIGNORE='&:ls:cd ~:cd ..:pwd:clear:[bf]g:exit:h:history'

# History: timestamps for later analysis. www.debian-administration.org/users/rossen/weblog/1
HISTTIMEFORMAT='%F %T '

# History: when the shell exits, append to the history file instead of overwriting it
shopt -s histappend

# After each command, append to the history file and reread it
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; #history -c; history -r"

# Prompt
PS1='[\u@\h \W]\$ '
#PS1="[\!]\[\033[1;25m\][\t]\[\033[1;33m\]\u\[\033[0m\]@\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\`\H\[\033[0m\]:\[\033[1;25m\]<\w>\[\033[0m\]# "

# PS2: continuation interactive prompt
PS2='  '

# PS4: prefix tracing output (set -x)
PS4='$0.$LINENO+ '

# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    # shellcheck disable=SC1091
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    # shellcheck disable=SC1091
    . /etc/bash_completion
  fi
fi

