#!/usr/bin/env bash


# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";
# 256-color terminal
export TERM='xterm-256color'
# Editor
export EDITOR='vim'
# Pager
export PAGER='less'  # Quit if only 1 screen, show colors, don't clear
export LESS='-FMnqrX'
# Colorize ls
export CLICOLOR=1
export CLICOLOR_FORCE=1  # Always show colors (with less and grep), Experimental

